# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436676c402dbaea0aacc7939586ba7b6562d4ea3f5832eec43057c0e39b3b20c4ba2bd512e778c2d03de1dd203554bf938783e7be7877a2dd2187886e7c51b4d

test:
  secret_key_base: 733cfb9a6296dd5c593c4ab52a94d13a48cb47cac280a5ec32a3ee816115e4a4041542ea1346a5789aff0e18b25c353f69f4e3e0f122e33b1c7b02619fae616c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
